name: payrillium-panel
services:
  payrillium-panel:
    image: nginx:alpine
    container_name: payrillium-panel
    ports:
      - target: 80
        published: "8338"
        protocol: tcp
    environment:
      - TZ=America/New_York
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID
        target: /usr/share/nginx/html
x-casaos:
  architectures:
    - amd64
    - arm64
  description:
    en_us: Frontend placeholder for PayOS testing and development
    es_es: Frontend placeholder para pruebas y desarrollo de PayOS
  icon: https://raw.githubusercontent.com/Payrillium/payrillium-store/main/Apps/PayrilliumPanel/icon.png
  tagline:
    en_us: PayOS frontend testing environment
    es_es: Entorno de pruebas frontend para PayOS
  author: Payrillium
  category: Payrillium
  hostname: ""
  index: /
  port_map: "8338"
  scheme: http
  store_app_id: payrillium-panel
  title:
    en_us: Payrillium Panel
    es_es: Panel Payrillium
